### PR TITLE
Unfloralize your repo

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by ineol** [comment]
:(

**Comment by progval** [comment]
Why did you close it instead of merge it?

**Comment by ilsordo** [comment]
We like flowers.

Le Mar 12 Mai 2015 13:32, Valentin Lorentz notifications@github.com a
écrit :

**Comment by progval** [comment]
:(

**Comment by ilsordo** [comment]
:tulip:

**Comment by progval** [comment]
:rose:

**Pull request closed without merging**
